/**
 * Validation schemas index
 * Central export point for all validation schemas
 */

// Search validation schemas
export {
  airportSchema,
  departureDateSchema,
  returnDateSchema,
  flightSegmentSchema,
  passengerCountSchema,
  oneWaySearchSchema,
  roundTripSearchSchema,
  multiCitySearchSchema,
  searchCriteriaSchema,
  validateSearchCriteria,
  validatePassengerCount,
  validateAirport,
  validateDepartureDate,
  type AirportInput,
  type FlightSegmentInput,
  type PassengerCountInput,
  type OneWaySearchInput,
  type RoundTripSearchInput,
  type MultiCitySearchInput,
  type SearchCriteriaInput,
} from "./search";

// Passenger validation schemas
export {
  contactInfoSchema,
  passportInfoSchema,
  createPassportSchemaWithTravelDate,
  basePassengerInfoSchema,
  domesticPassengerSchema,
  internationalPassengerSchema,
  createInternationalPassengerSchema,
  primaryDomesticPassengerSchema,
  primaryInternationalPassengerSchema,
  createPrimaryInternationalPassengerSchema,
  domesticPassengerListSchema,
  internationalPassengerListSchema,
  createInternationalPassengerListSchema,
  validatePassengerAge,
  createPassengerSchemaWithAgeValidation,
  validateContactInfo,
  validatePassportInfo,
  validatePassengerInfo,
  validatePassengerList,
  type ContactInfoInput,
  type PassportInfoInput,
  type BasePassengerInfoInput,
  type DomesticPassengerInput,
  type InternationalPassengerInput,
  type PrimaryDomesticPassengerInput,
  type PrimaryInternationalPassengerInput,
} from "./passenger";

// Payment validation schemas
export {
  cardNumberSchema,
  expiryDateSchema,
  cvvSchema,
  cardholderNameSchema,
  paymentInfoSchema,
  billingAddressSchema,
  completePaymentSchema,
  validateCardNumber,
  validateExpiryDate,
  validateCvv,
  validateCardholderName,
  validatePaymentInfo,
  validateBillingAddress,
  validateCompletePayment,
  detectCardType,
  formatCardNumber,
  maskCardNumber,
  type CardNumberInput,
  type ExpiryDateInput,
  type CvvInput,
  type CardholderNameInput,
  type PaymentInfoInput,
  type BillingAddressInput,
  type CompletePaymentInput,
} from "./payment";
